echo "# AUTOGENERATED using: scripts/generate_thrift_meta.sh" > $1
echo "SaiMetadata = {" >> $1
cat ../SAI/test/saithriftv2/build/lib/sai_thrift/sai_adapter.py | grep -e "attrs\[\"SAI_.*" | sed 's/ attrs\[//' | sed 's/\] = attr\.value\./: \"/' | sed 's/$/",/' >> $1
echo "}" >> $1
