name: sc-docker-common-bldr

on:
#  push:
#    branches: [ "**" ]
#    paths:
#      - '.github/workflows/sc-docker-common-bldr.yml'
#      - 'dockerfiles/Dockerfile'
#      - 'npu/broadcom/trident2/saivs/Dockerfile'
#      - 'common/'
#      - 'builds/'
#      - 'cli/'
#      - 'scripts/'
#      - 'configs/'
#      - 'setup.py'
#      - 'build.sh'
#      - '.dockerignore'
  pull_request:
    branches: [ "**" ]
    paths:
      - '.github/workflows/sc-docker-common-bldr.yml'
      - 'dockerfiles/Dockerfile'
      - 'npu/broadcom/trident2/saivs/Dockerfile'
      - 'common/'
      - 'builds/'
      - 'cli/'
      - 'scripts/'
      - 'configs/'
      - 'setup.py'
      - 'build.sh'
      - '.dockerignore'
  
jobs:
  
  build-sc-client-thrift:
    name: Build SAI Challenger client thrift image
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v3
    - name: submodules update
      run: git submodule update --init
    - name: build docker image
      run: |
       ./build.sh -i client -s thrift
  
  build-sc-standalone:
    name: Build SAI Challenger standalone image
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v3
    - name: submodules update
      run: git submodule update --init
    - name: build docker image
      run: |
        ./build.sh -i standalone 
  
  build-sc-stadalone-thrift:
    name: Build SAI Challenger standalone thrift image
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v3
    - name: submodules update
      run: git submodule update --init
    - name: build docker image
      run: |
       ./build.sh -i standalone -s thrift
  
  build-sc-server:
    name: Build SAI Challenger server image
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v3
    - name: submodules update
      run: git submodule update --init
    - name: build docker image
      run: |
       ./build.sh -i server
       
  build-sc-server-thrift:
    name: Build SAI Challenger server thrift image
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v3
    - name: submodules update
      run: git submodule update --init
    - name: build docker image
      run: |
       ./build.sh -i server -s thrift
