name: sc-docker-client-bldr

on:
  pull_request:
    types: [synchronize]
      branches: [ "**" ]
      paths:
        - '.github/workflows/sc-docker-client-bldr.yml'
        - 'dockerfiles/Dockerfile.client'
  workflow_dispatch:
  
jobs:
  
  build-sc-client-thrift:
    name: Build SAI Challenger client thrift image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: submodules update
      run: git submodule update --init
    - name: build docker image
      run: |
       ./build.sh -i client
