name: sc-docker-standalone-bldr

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "**" ]
    paths:
      - '.github/workflows/sc-docker-standalone-bldr.yml'
      - 'dockerfiles/Dockerfile'
      - 'npu/broadcom/trident2/saivs/Dockerfile'
      - 'npu/broadcom/trident2/saivs/Dockerfile.saithrift'
      - 'common/'
      - 'builds/'
      - 'cli/'
      - 'scripts/'
      - 'configs/'
      - 'setup.py'
      - 'build.sh'
      - '.dockerignore'
  
jobs:   
  build-sc-stadalone-thrift:
    name: Build SAI Challenger standalone image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: submodules update
      run: git submodule update --init
    - name: build standalone docker image
      run: ./build.sh -i standalone
    - name: run docker image
      run: ./run.sh -a trident2 -t saivs 
    - name: setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: sleep
      run: sleep 60s
    - name: run tests
      run: ./exec.sh -t saivs pytest --testbed=saivs_standalone -v -k "test_l2_basic"
